### ISSUE TITLE
interface not visible

### ISSUE THREAD

**Issue by masonbesmer** [JVital2013/RoadApplePi#3]
https://prnt.sc/mvrqdg

using pi 3b+ fresh install of everything & this is what it shows when going to the hostname

**Comment by tomhorak** [comment]
I have the same issue.  It looks like the install script failed.  I get 

Step 4. Building and installing RoadApplePi
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'install'.  Stop.
cp: cannot stat 'html': No such file or directory
rm: cannot remove '/var/www/html/index.html': No such file or directory
cp: cannot stat 'raprec.service': No such file or directory
chown: cannot access '/lib/systemd/system/raprec.service': No such file or directory
chmod: cannot access '/lib/systemd/system/raprec.service': No such file or directory
Failed to enable unit: File raprec.service: No such file or directory
cp: cannot stat 'hostapd-rap.conf': No such file or directory
cp: cannot stat 'dnsmasq.conf': No such file or directory
mkdir: cannot create directory ‘/var/www/html/vids’: File exists
cp: cannot stat 'roadapplepi.sql': No such file or directory
ERROR 1046 (3D000) at line 1: No database selected
Done! Please reboot your Raspberry Pi now

**Comment by tomhorak** [comment]
That is from my 2nd attempt.  My first attempt it just rebooted so I didn't see how it ended.  I tried to manually copy the html files to /var/www/html.  I can now see the interface but nothing really works.  I'm sure because there is no binary etc.

**Comment by leonardzh** [comment]
I delete cd .. in step 4 and it works. But fail to change it to access point under noobs os

**Comment by jonathanbun** [comment]
Did anyone get this to work? I'm running into the same issue.
